In [4]:
import os
import sys
sys.path.append('../..')
sys.path.append('../../RecStudio')
import pickle
import torch
import numpy as np

with open('Goodreads_rating.pkl', 'rb') as f:
        trn_set = pickle.load(f)
        val_set = pickle.load(f)
        dataset = pickle.load(f)

In [3]:
dataset.item_feat

,book_id,country_code,is_ebook,publication_year,work_id,ratings_count,num_pages,publisher,average_rating,title,description
0,0,0,0,0,0,0,0,0,0,,
1,1,1,2,19,77052,3,1,501,5,Detection Unlimited (Inspector Hemingway Myste...,Slumped on a seat under an oak tree is old Sam...
2,2,1,2,0,66689,1,5,0,5,"Gone (Wake, #3)",There is an alternate cover edition for this I...
3,3,1,1,16,26455,1,4,195,4,"Turned at Dark (Shadow Falls, #0.5)",Independent and strong-willed Della Tsang did ...
4,4,1,2,0,186329,1,3,0,1,One L: The Turbulent True Story of a First Yea...,"Newsweekcalls him ""an extraordinarily canny an..."
...,...,...,...,...,...,...,...,...,...,...,...
366358,366358,1,1,7,80579,3,4,0,2,Brightest Shadow The Mythical Knights Book 1,"After the death of his father, David Drigan wo..."
366359,366359,1,2,9,139794,3,5,20375,2,Dissected,"Abandoned by her mother at a young age, sevent..."
366360,366360,1,1,11,116847,3,2,3615,2,Happily Ever Afters,Lainey Stratton does not fall in love with str...
366361,366361,1,2,0,46567,5,3,0,3,Canasta de Cuentos Mexicanos,Canasta de cuentos mexicanoses el producto de ...
366362,366362,1,1,0,103922,1,3,0,5,Proof of Heaven: A Neurosurgeon's Journey into...,A SCIENTIST'S CASE FOR THE AFTERLIFE\nNear-dea...

In [3]:
dataset.item_feat

,book_id,country_code,is_ebook,publication_year,work_id,ratings_count,num_pages,publisher,average_rating,title,description
0,0,0,0,0,0,0,0,0,0,,
1,1,1,2,19,77052,3,1,501,5,Detection Unlimited (Inspector Hemingway Myste...,Slumped on a seat under an oak tree is old Sam...
2,2,1,2,0,66689,1,5,0,5,"Gone (Wake, #3)",There is an alternate cover edition for this I...
3,3,1,1,16,26455,1,4,195,4,"Turned at Dark (Shadow Falls, #0.5)",Independent and strong-willed Della Tsang did ...
4,4,1,2,0,186329,1,3,0,1,One L: The Turbulent True Story of a First Yea...,"Newsweekcalls him ""an extraordinarily canny an..."
...,...,...,...,...,...,...,...,...,...,...,...
366358,366358,1,1,7,80579,3,4,0,2,Brightest Shadow The Mythical Knights Book 1,"After the death of his father, David Drigan wo..."
366359,366359,1,2,9,139794,3,5,20375,2,Dissected,"Abandoned by her mother at a young age, sevent..."
366360,366360,1,1,11,116847,3,2,3615,2,Happily Ever Afters,Lainey Stratton does not fall in love with str...
366361,366361,1,2,0,46567,5,3,0,3,Canasta de Cuentos Mexicanos,Canasta de cuentos mexicanoses el producto de ...
366362,366362,1,1,0,103922,1,3,0,5,Proof of Heaven: A Neurosurgeon's Journey into...,A SCIENTIST'S CASE FOR THE AFTERLIFE\nNear-dea...

In [4]:
dataset.item_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366363 entries, 0 to 366362
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   book_id           366363 non-null  int64
 1   country_code      366363 non-null  Int64
 2   is_ebook          366363 non-null  Int64
 3   publication_year  366363 non-null  Int64
 4   work_id           366363 non-null  Int64
 5   ratings_count     366363 non-null  Int64
 6   num_pages         366363 non-null  Int64
 7   publisher         366363 non-null  Int64
 8   average_rating    366363 non-null  Int64
 9   title             366363 non-null  object
 10  description       366363 non-null  object
dtypes: Int64(8), int64(1), object(2)
memory usage: 33.5+ MB

In [6]:
sum(dataset.item_feat['description'] == '')

22734

In [7]:
sum(dataset.item_feat['title'] == '')

1

In [2]:
from langdetect import detect

def is_english(text):
    try:
        return detect(text) == 'en'
    except:
        return False